### ISSUE TITLE
Scenario2-Task2-CurvePath (Missing Prefab)

### ISSUE THREAD

**Issue by ZhaoLizz** [VRatPolito/LocomotionVR#1]
As shown in the picture, when I open Scenario2, CurvePath is Missing Prefab.
I am using Unity version 2018.4.28f1 in Win10.
And Scenario1 can work fine.
How do I fix it? Thank you in advance!

![curvepath](https://user-images.githubusercontent.com/29300861/117997639-b8542580-b375-11eb-9f9c-ed0b466d61f4.png)

**Comment by DavideCalandra** [comment]
Hi @ZhaoLizz , we checked it and the prefab is not missing for us. CurvedPath is a .blend file, so since Unity requires Blender to correctly import them, try install it on your pc and then reloading the project (we will add it to the readme).

**Comment by ZhaoLizz** [comment]
Thank you for your reply!@Cryst4lDr4g0n 
I downloaded Blender and re-imported the three CurvePath.blend* files as you instructed, and now CurvePath prefab is working properly. Thank you very much!
![curvepath asset](https://user-images.githubusercontent.com/29300861/118013909-35d36200-b385-11eb-9168-7f0acb1f5b11.png)
